### ISSUE TITLE
Quarkus Resteasy Problem is still flagged as experimental

### ISSUE THREAD

**Issue by chberger** [quarkiverse/quarkus-resteasy-problem#316]
The extension is still flagged as [experimental](https://github.com/TietoEVRY/quarkus-resteasy-problem/blob/master/runtime/src/main/resources/META-INF/quarkus-extension.yaml#L14). Although this is just a meta description, it could be a bit daunting for a developer as the extension looks like this at the dev-ui.

![image](https://github.com/TietoEVRY/quarkus-resteasy-problem/assets/3606282/778aa6d9-c5f2-4500-a48e-47b7c41aeb01)

**Comment by lwitkowski** [comment]
I would call it stable, the only hesitation is - when we finally decide to move this project to Quarkiverse it will most likely end up in EXPERIMENTAL status again...

**Comment by suchwerk** [comment]
When will you move it to Quarkiverse?

**Comment by geoand** [comment]
Definitely +1 for including this in the Quarkiverse

**Comment by maxandersen** [comment]
whats blocking from moving to quarkiverse? 

note - its for sure not a requirement to be in quarkiverse hub to show up in code.quarkus. 

I'm wondering if we shouldn't have this be part of core quarkus-rest?

**Comment by lwitkowski** [comment]
> whats blocking from moving to quarkiverse?

@geoand @maxandersen None of us maintainers of this extension work at Tietoevry anymore, and infra folks that helped us make this code public in Tietoevry github organisation are also gone, so it can be tricky for me to reach someone, who could migrate this project into quarkiverse org, which would allow us to keep nice 60 github stars :) On the other hand we can simply fork it into quarkiverse.

I'll try to reach someone who knows someone regarding project migration, if this doesn't work, we'll proceed with a fork.

**Comment by lwitkowski** [comment]
@geoand @maxandersen sorry it took so long. After some internal discussions we would like to proceed with moving this extension to quarkiverse, although we will not migrate this github repo, w're going to archive this one and copy over source code into empty quarkiverse project.

How can we proceed here? Who could assist us with setting up a project in quarkiverse?

cc @pazkooda

**Comment by geoand** [comment]
That's very nice to hear!

@gastaldi is the OG of Quarkiverse :)

**Comment by gastaldi** [comment]
I can provision a new repository there, too bad we'll miss the GitHub stars. I can also move the repository there to preserve the stars if you make me an admin for this repository. Let me know what you prefer

**Comment by lwitkowski** [comment]
@gastaldi let's move the repo then, I've just added you as an admin.

**Comment by lwitkowski** [comment]
The migration is complete, and the extension itself is no longer experimental, so I'm closing this issue. Thanks everyone for participation (and motivation :))
