### ISSUE TITLE
Quarkiverse adjustments

### ISSUE THREAD

**Issue by lwitkowski** [quarkiverse/quarkus-resteasy-problem#397]
https://github.com/quarkiverse/quarkiverse/wiki#getting-an-extension-onboarded
https://quarkus.io/guides/writing-extensions#ecosystem
https://hub.quarkiverse.io/checklist/#after-the-repository-is-created

- [x] change maven artifact group/name/version
- [x] change java package names
- [x] update README.md and CONTRIBUTING.md
- [x] Create an Ecosystem CI issue
- [x] Create a quarkiverse-resteasy-problem/info.yaml file in Ecosystem CI repository
- [x] make Ecosystem CI run green
- [x] tag/branch 3.9 for critical bugfixes of the standalone version
- [x] Publish binaries to maven repository
- [x] Add extension to quarkus-extension-catalog repository

**Comment by pazkooda** [comment]
@gastaldi Feel free to supplement task list 😉 ...

**Comment by lwitkowski** [comment]
First snapshot published: https://s01.oss.sonatype.org/content/repositories/snapshots/io/quarkiverse/resteasy-problem/quarkus-resteasy-problem/

**Comment by lwitkowski** [comment]
Add extension to quarkus-extension-catalog repository: https://github.com/quarkusio/quarkus-extension-catalog/pull/110
