### ISSUE TITLE
move javax.annotation.* to jakarta.annotation.*

### ISSUE THREAD

**Issue by cvgaviao** [quarkiverse/quarkus-resteasy-problem#435]
**Is your feature request related to RFC7807? Please describe.**
The current version of this project is using:
```
<dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <version>${jsr305.version}</version>
        </dependency>
```
 
Unfortunately this is providing `javax.annotation` package.

The quarkus 3.15.1 is using `jakarta.annotation` from: 

```
 <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
```

**Describe the solution you'd like**
Use the same package being used by Quarkus

**Comment by lwitkowski** [comment]
@cvgaviao thanks for reporting this, well spotted! I've just merged this change into main, it will be included in the next release
